### ISSUE TITLE
How should we handle deploying new serverless endpoints in Go.cd?

### ISSUE THREAD

**Issue by patrickbrandt** [C0k3/session#11]
The `sls deploy function` command requires that a full `sls deploy` be executed first. This is because the `sls deploy` command is responsible for building the CFT that creates the lambda function and APIG resources.

How do we ensure that a pipeline for a newly created function doesn't introduce the side-effect of updating all other existing functions via a `sls deploy`?

**Comment by clearly** [comment]
Introduced per function based deployments

**Comment by patrickbrandt** [comment]
Hi @clearly:

This is still an open question. When I add a new function to the pipeline (one that has not yet been deployed), this is the error that serverless returns:

![image](https://cloud.githubusercontent.com/assets/11197026/20407408/443060fc-acdf-11e6-8c62-981757b794b2.png)

Serverless requires a full ```sls deploy``` for new functions.

**Comment by patrickbrandt** [comment]
@clearly created two new pipelines:

1. manual dev stack deployment
2. manual test stack deployment

Should any builds fail due to the fact that a function stack has not yet been deployed, the development team can manually deploy the full stack first in order to proceed with per-function deployments.
